version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: chatbot-image
    volumes:
      - ./src:/src
      - ./templates:/templates
      - ./tests:/tests
    entrypoint:
      - /venv/bin/chatbot
    ports:
      - 8000:8000
    env_file:
      - envs/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-data:/data/db